services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      - PUID=996
      - PGID=988
      - TZ=America/New_York
    volumes:
      - /mnt/data/docker/volumes/nginx-proxy-manager/data:/data
      - /mnt/data/docker/volumes/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    restart: unless-stopped
